apiVersion: v1
kind: Service
metadata:
  name: appointments-backend
  namespace: appointments
spec:
  selector:
    app: appointments-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
